import * as THREE from './../libs/three.module.min.js';
import { BodyType } from './../sceneSubjects/astronomicalBodies/Stars.js';

export const systems = {
	doomspace:
	{
		planets:
			[
				{
					name: "Valt",
					size: 8,
					distanceX: 100,
					texture: "assets/textures/fantasy1/p3.jpg",
					rotationSpeed: 0.08,
					revolutionSpeed: 0.01,
					revolutionSpeedOffset: -0.5,
					revolutionTiltAngle: -40,
					selfTilt: 0,
					moons: []
				},
				{
					name: "Fyreen",
					size: 16,
					distanceX: 200,
					texture: "assets/textures/fantasy1/p7.jpg",
					rotationSpeed: 0.08,
					revolutionSpeed: 0.01,
					revolutionSpeedOffset: -1,
					revolutionTiltAngle: -40,
					selfTilt: 0,
					moons: [
						{
							name: "Crios",
							size: 3,
							distanceX: 32,
							texture: "assets/textures/fantasy1/p4.webp",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0,
							revolutionTiltAngle: 40,
							selfTilt: 0,
						},

					]
				},
				{
					name: "Malas",
					size: 20,
					distanceX: 400,
					texture: "assets/textures/fantasy1/water1.jpg",
					rotationSpeed: 0.08,
					revolutionSpeed: 0.01,
					revolutionSpeedOffset: -3,
					revolutionTiltAngle: -40,
					selfTilt: 0,
					moons: [
						{
							name: "Shard",
							size: 3,
							distanceX: 32,
							texture: "assets/textures/fantasy1/p1.jpg",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0,
							revolutionTiltAngle: 40,
							selfTilt: 0,
						},

					]
				},
				{
					name: "En",
					size: 0.0001,
					distanceX: 600,
					texture: "assets/textures/fantasy1/p3.jpg",
					rotationSpeed: 0.08,
					revolutionSpeed: 0.01,
					revolutionSpeedOffset: 0.5415,
					revolutionTiltAngle: -40,
					selfTilt: 0,
					moons: [
						{
							name: "Aruun",
							size: 3,
							distanceX: 12,
							texture: "assets/textures/fantasy1/p4.webp",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0,
							revolutionTiltAngle: 50,
							selfTilt: 0,
						},
						{
							name: "G'vek",
							size: 2,
							distanceX: 32,
							texture: "assets/textures/fantasy1/moon1.jpeg",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 1,
							revolutionTiltAngle: 222,
							selfTilt: 0,
						},
						{
							name: "Inivar",
							size: 1.8,
							distanceX: 45,
							texture: "assets/textures/fantasy1/p5.webp",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: -2,
							revolutionTiltAngle: 83,
							selfTilt: 0,
						},
						{
							name: "Lesk",
							size: 2.2,
							distanceX: 62,
							texture: "assets/textures/fantasy1/moon5.avif",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0.5,
							revolutionTiltAngle: 90,
							selfTilt: 0,
						},
						{
							name: "Shalar",
							size: 1.5,
							distanceX: 87,
							texture: "assets/textures/fantasy1/moon2.jpeg",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 1,
							revolutionTiltAngle: 0,
							selfTilt: 0,
						},
						{
							name: "Thrydd",
							size: 2.8,
							distanceX: 111,
							texture: "assets/textures/fantasy1/moon3.avif",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0,
							revolutionTiltAngle: 40,
							selfTilt: 0,
						},
						{
							name: "Vocath",
							size: 2.9,
							distanceX: 130,
							texture: "assets/textures/fantasy1/moon4.jpeg",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: -0.5,
							revolutionTiltAngle: 140,
							selfTilt: 0,
						},
						{
							name: "Yisheen",
							size: 2.3,
							distanceX: 145,
							texture: "assets/textures/fantasy1/moon7.png",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 2,
							revolutionTiltAngle: 63,
							selfTilt: 0,
						},
						{
							name: "Yort",
							size: 1.3,
							distanceX: 160,
							texture: "assets/textures/fantasy1/moon6.webp",
							rotationSpeed: 0.08,
							revolutionSpeed: 0.1,
							revolutionSpeedOffset: 0,
							revolutionTiltAngle: 80,
							selfTilt: 0,
						},
					]
				}
			],
		stars: [
			{}, // default grey stars 
			{
				center: new THREE.Vector3(700, 700, 200),
				rotation: new THREE.Vector3(0, 30, 0),
				radius: 300,
				numStars: 1000,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [0.75, 0.889],
				satSpecturm: [1, 1],
				lightnessSpectrum: [0.6, 0.8],
				sizeRange: [5, 12],
				capsuleHeightFactor: 4
			},
			{
				center: new THREE.Vector3(-700, -200, 800),
				rotation: new THREE.Vector3(0, 0, 90),
				radius: 200,
				numStars: 200,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [20 / 360, 50 / 360],
				satSpecturm: [1, 1],
				lightnessSpectrum: [0.6, 0.8],
				sizeRange: [5, 12],
				capsuleHeightFactor: 4
			},
			{
				center: new THREE.Vector3(1200, -100, -800),
				rotation: new THREE.Vector3(90, 30, 20),
				radius: 200,
				numStars: 200,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [25 / 360, 70 / 360],
				satSpecturm: [0.8, 0.85],
				lightnessSpectrum: [0.65, 0.7],
				sizeRange: [5, 12],
				capsuleHeightFactor: 4
			}
		],
		sun: {
			color: 0xFFFFFF,
			intensity: 11110.91,
			name: "sun",
			size: 20,
			texturePath: "assets/textures/sun.jpg",
			illuminated: true
		}
	},
	realmspace:
	{
		planets: [
			{
				name: "Anadia",
				description: "One of the two Dawn Heralds, this small, amber-and-green-colored planet[1] was closest to the sun and mostly populated by halflings and umber hulks. It was covered in canyons that dwarfed the Great Rift, and the equatorial regions were unlivable because of the sun's proximity.",
				size: 8,
				distanceX: 100,
				texture: "assets/textures/fantasy1/p3.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: -0.5,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: []
			},
			{
				name: "Coliar",
				description: "Coliar was a gas giant mostly populated with avian life-forms and other flying creatures. Floating islands of water and earth revolved around the planet's core. Elminster was said to own a resort on one of these islands.[7] The planet was covered with clouds and appeared as a gray-white sphere from Toril. It was considered one of the Dawn Heralds.",
				size: 10,
				distanceX: 200,
				texture: "assets/textures/fantasy1/p7.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: -0.7,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: [
				]
			},
			{
				name: "Toril",
				description: "The third planet in the system was the most populated, teeming with life. Approximately 60% of the surface being covered with water, fauna on Toril ranged from creatures living in the air, on the land, under the water and subterranean habitats. This planet was formerly known as Abeir-Toril.",
				size: 16,
				distanceX: 400,
				texture: "assets/textures/fantasy1/p7.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: -1,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: [
					{
						name: "Selûne",
						description: "Selûne was Toril's largest natural satellite.[1][11] It orbited about 183,000 miles (295,000 kilometers) from Toril,[11] although some sages from the late 14th century DR claimed that its orbital distance was only about 20,000 miles (32,000 kilometers).[1][note 1] Only one side of it ever faced the planet; the other side was called the 'dark side', yet it was not always dark. This was where most activity took place. Although Torilians had named it after the deity Selûne, the moon's own inhabitants named their home after Leira. Trailing in the orbit of this satellite were the Tears of Selûne.",
						size: 3,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},

				]
			},
			{
				name: "Karpri",
				description: "The first of the Five Wanderers, Karpri,[1] the fourth planet in the system, was an oceanic world. It was an absolutely beautiful place to behold from wildspace.[12] From Toril it appeared as a large star but as a sapphire ball with white caps when viewed by magical means.[1] The poles were covered in pack ice hundreds of miles thick and stalked by deadly cold-loving predators, while floating on the equator's waters could be found seaweed, which at some points could support up to five tons of weight but were also home to massive, dangerous insects. The waters of the world were inhabited by aquatic elves and predacious sea life, making this planet as dangerous as it was beautiful.",
				size: 12,
				distanceX: 600,
				texture: "assets/textures/neptune.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: -3,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: [
				]
			},
			{
				name: "Chandos",
				description: "The next of the Five Wanderers,[1] Chandos was another oceanic world. Its seas contained lumps of rock that, when piled high enough, created highly unstable islands. Those living on these islands were the human, dwarven, and orcish descendants from a pair of spelljammers that crash-landed here long ago. Over time, they lost their technologies and developed an enmity for each other, forgetting their pasts and becoming primitive.[13] From Toril, this planet appeared as a greenish-brown smudge, which changed over time.",
				size: 20,
				distanceX: 800,
				texture: "assets/textures/neptune.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: 0.5,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: [
				]
			},
			{
				name: "Glyth",
				description: "The third of the Five Wanderers was a gray planet that had a beautiful ring and three satellites observable from Toril.[1] In truth, Glyth was a harsh, ringed planet that, as of the mid-14th century DR, had been occupied by the dreaded illithid for about a century.[14] Plant life was continually burned by the harsh atmosphere or by the mind flayers to prevent their humanoid cattle hiding from them. A remarkably pure, edible gelatin 'water' could be found in the place of seas, and while the planet still had ice caps as normal, nothing lived there. Most activity occured underground. As well as the planet's rings[15], Glyth was orbited by three satellites. One, known as Haven,[15] was a hollowed out asteroid and treated as neutral ground for the different mind flayer factions. Another, Mingabwe,[16] was a trading port for non-illithids. Orbiting Mingabwe was Polluter, an unmapped asteroid. A group of over 300 mercenaries from the Code Helm resided here conducting raids against illithids in the system.",
				size: 15,
				distanceX: 1900,
				texture: "assets/textures/neptune.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: 0.5,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				moons: [
					{
						name: "m1",
						description: "",
						size: 1,
						distanceX: 22,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m2",
						description: "",
						size: 2,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: -1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m3",
						description: "",
						size: 2.5,
						distanceX: 38,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
				]
			},
			{
				name: "Garden",
				description: "Garden was not actually a planet. It was a series of earthy-masses connected together by a massive plant. Non-sentient life-forms created a balanced ecosystem with the many varieties of plant life growing here, but otherwise it was populated by pirates. Garden was also orbited by twelve satellites.[18] Garden could rarely be seen from Toril, but when it was spotted, it appeared as a tiny green speck",
				size: 10,
				distanceX: 2300,
				texture: "assets/textures/neptune.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: 0.5,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				illuminated: false,
				moons: [
					{
						name: "m1",
						description: "",
						size: 1,
						distanceX: 22,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m2",
						description: "",
						size: 2,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: -1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m3",
						description: "",
						size: 2.5,
						distanceX: 38,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m4",
						description: "",
						size: 2.5,
						distanceX: 45,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m5",
						description: "",
						size: 1,
						distanceX: 22,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0.5,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m12",
						description: "",
						size: 2,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: -0.5,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m6",
						description: "",
						size: 2.5,
						distanceX: 38,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1.5,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m7",
						description: "",
						size: 2.5,
						distanceX: 45,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1.5,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m8",
						description: "",
						size: 1,
						distanceX: 22,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m9",
						description: "",
						size: 2,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m10",
						description: "",
						size: 2.5,
						distanceX: 38,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 2,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m11",
						description: "",
						size: 2.5,
						distanceX: 45,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 2,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
				]
			},
			{
				name: "H'Catha",
				description: "The last of Toril's Five Wanderers, H'Catha, appeared as a crystalline glimmer of white.[1] Consisting of a flat disc of 300‑mile-thick (480‑kilometer) water with a single mountain in the center, close-up, this world looked like a giant wagon wheel, with the Spindle (the mountain) always pointing directly at the sun. Near the base of the mountain, six ports, each owned by a different type of beholder accepted spelljamming traffic from non-H'Cathan beholders and the Arcane. Other species were only allowed to land if they had goods to trade and left as soon as they were done. The world was orbited by two satellites, Turnbetl and Lumbe.",
				size: 22,
				distanceX: 3000,
				texture: "assets/textures/neptune.jpg",
				rotationSpeed: 0.08,
				revolutionSpeed: 0.01,
				revolutionSpeedOffset: 0.5,
				revolutionTiltAngle: -40,
				selfTilt: 0,
				
				moons: [
					{
						name: "m1",
						description: "",
						size: 1,
						distanceX: 32,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: 0,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
					{
						name: "m2",
						description: "",
						size: 2,
						distanceX: 42,
						texture: "assets/textures/fantasy1/p4.webp",
						rotationSpeed: 0.08,
						revolutionSpeed: 0.1,
						revolutionSpeedOffset: -1,
						revolutionTiltAngle: 40,
						selfTilt: 0,
					},
				]
			},

		],
		stars: [
			{}, // default grey stars 
			{
				center: new THREE.Vector3(700, 1200, 200),
				rotation: new THREE.Vector3(0, 30, 0),
				radius: 500,
				numStars: 4000,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [0.75, 0.889],
				satSpecturm: [1, 1],
				lightnessSpectrum: [0.6, 0.8],
				sizeRange: [5, 12],
				capsuleHeightFactor: 6
			},
			{
				center: new THREE.Vector3(-1700, 700, 800),
				rotation: new THREE.Vector3(0, 0, 90),
				radius: 200,
				numStars: 200,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [20 / 360, 40 / 360],
				satSpecturm: [1, 1],
				lightnessSpectrum: [0.6, 0.8],
				sizeRange: [5, 12],
				capsuleHeightFactor: 4
			},
			{
				center: new THREE.Vector3(1200, -100, -800),
				rotation: new THREE.Vector3(90, 30, 20),
				radius: 200,
				numStars: 200,
				bodyType: BodyType.CAPSULE,
				hueSpectrum: [25 / 360, 70 / 360],
				satSpecturm: [0.8, 0.85],
				lightnessSpectrum: [0.65, 0.7],
				sizeRange: [5, 12],
				capsuleHeightFactor: 4
			}
		],
		sun: {
			color: 0xFFFFFF,
			intensity: 111100.91,
			name: "sun",
			size: 20,
			texturePath: "assets/textures/sun.jpg",
			illuminated: true
		}
	}
}